apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJhY3JncmVldGluZ2xhYmRzLmF6dXJlY3IuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJhY3JncmVldGluZ2xhYmRzIiwKICAgICAgInBhc3N3b3JkIjogInJDVm9LWWl1L0g4Y3RoUDEraDBVR2haNFFKWXNNYW9qYmZQcDNRNU92ZCtBQ1JCVUhaQU8iLAogICAgICAiYXV0aCI6ICJZV055WjNKbFpYUnBibWRzWVdKa2N6cHlRMVp2UzFscGRTOUlPR04wYUZBeEsyZ3dWVWRvV2pSUlNsbHpUV0Z2YW1KbVVIQXpVVFZQZG1RclFVTlNRbFZJV2tGUCIKICAgIH0KICB9Cn0K