apiVersion: v1
kind: Service
metadata:
  name: redis  # The Greetings App will resolve Redis using this name
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
